[versions]
kotlin = "2.1.20"
kover = "0.9.1"
detekt = "1.23.8"
semver = "0.16.0"
jreleaser = "1.17.0"
jmh = "0.7.3"
junit-jupiter = "5.11.4"
assertj = "3.27.3"
mockk = "1.13.17"

[libraries]
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit-jupiter" }
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }

[bundles]
junit-jupiter = ["junit-jupiter-api", "junit-jupiter-params"]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
semver = { id = "com.github.jmongard.git-semver-plugin", version.ref = "semver" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }
jmh = { id = "me.champeau.jmh", version.ref = "jmh" }
